# Generated by Django 5.1.10 on 2026-07-02 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id_number', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Cow', 'Cow'), ('Ox', 'Ox'), ('Buffalo', 'Buffalo'), ('Calf', 'Calf'), ('Heifer', 'Heifer'), ('Bull', 'Bull')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('current_value', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('health_status', models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('Treatment', 'Treatment'), ('Pregnant', 'Pregnant')], default='Healthy', max_length=50)),
                ('vaccinated', models.BooleanField(default=False)),
                ('vaccination_date', models.DateField(blank=True, null=True)),
                ('last_vaccination_type', models.CharField(blank=True, max_length=100)),
                ('pregnancy_status', models.CharField(default='Not Pregnant', max_length=50)),
                ('expected_delivery_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('image_url', models.URLField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='MilkProduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('production_date', models.DateField()),
                ('morning_milk', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('evening_milk', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('total_milk', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('quality_grade', models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C')], max_length=10)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-production_date', '-created_at'],
            },
        ),
    ]
