# Generated by Django 5.1.10 on 2026-07-09 00:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CapitalContribution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contribution_date', models.DateField()),
                ('source_type', models.CharField(choices=[('owner', 'owner'), ('investor', 'investor'), ('partner', 'partner'), ('other', 'other')], default='owner', max_length=20)),
                ('contributor_name', models.CharField(blank=True, max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('cash', 'cash'), ('bank_transfer', 'bank_transfer'), ('check', 'check')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('expected_return_note', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-contribution_date', '-created_at'],
            },
        ),
    ]
