# Generated by Django 5.1.10 on 2026-07-09 06:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def copy_withdrawals_to_personal_transactions(apps, schema_editor):
    family_withdrawal = apps.get_model("financial", "FamilyWithdrawal")
    personal_transaction = apps.get_model("financial", "PersonalTransaction")
    records = [
        personal_transaction(
            user_id=withdrawal.user_id,
            transaction_date=withdrawal.withdrawal_date,
            transaction_type="farm_transfer",
            category="farm_transfer",
            amount=withdrawal.amount,
            description=withdrawal.description or "Farm cash moved to personal pocket",
            source_withdrawal_id=withdrawal.id,
            created_at=withdrawal.created_at,
            updated_at=withdrawal.updated_at,
        )
        for withdrawal in family_withdrawal.objects.all()
    ]
    personal_transaction.objects.bulk_create(records, ignore_conflicts=True)


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0003_capitalcontribution'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_date', models.DateField()),
                ('transaction_type', models.CharField(choices=[('income', 'income'), ('expense', 'expense'), ('farm_transfer', 'farm_transfer')], max_length=20)),
                ('category', models.CharField(blank=True, choices=[('salary', 'salary'), ('household', 'household'), ('medical', 'medical'), ('education', 'education'), ('food', 'food'), ('transport', 'transport'), ('savings', 'savings'), ('farm_transfer', 'farm_transfer'), ('other', 'other')], max_length=50)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_withdrawal', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='personal_transaction', to='financial.familywithdrawal')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-transaction_date', '-created_at'],
            },
        ),
        migrations.RunPython(copy_withdrawals_to_personal_transactions, migrations.RunPython.noop),
    ]
