# Generated by Django 5.1.10 on 2026-07-09 06:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0004_personaltransaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventory',
            name='auto_deduct_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='inventory',
            name='daily_usage_quantity',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='inventory',
            name='last_auto_deducted',
            field=models.DateField(blank=True, null=True),
        ),
    ]
