# Generated by Django 5.1.10 on 2026-07-10 13:48

from django.db import migrations, models
from django.db.models import F


def mark_existing_sales_paid(apps, schema_editor):
    Sale = apps.get_model('financial', 'Sale')
    Sale.objects.filter(paid_amount=0).update(paid_amount=F('total_amount'))


class Migration(migrations.Migration):

    dependencies = [
        ('financial', '0005_inventory_auto_deduct_enabled_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.RunPython(mark_existing_sales_paid, migrations.RunPython.noop),
    ]
